### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by GanizaniSitara** [okria/okr-strapi#7]
After updates of packages to get succesfull compile. Database.json looks ok ...

`Building your admin UI with development configuration ...

√ Webpack
  Compiled successfully in 28.49s

[2020-10-17T21:42:01.183Z] debug ⛔️ Server wasn't able to start properly.
[2020-10-17T21:42:01.184Z] error TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.load (C:\Solutions\okr-strapi\node_modules\strapi-database\lib\connector-registry.js:17:39)
    at DatabaseManager.initialize (C:\Solutions\okr-strapi\node_modules\strapi-database\lib\database-manager.js:32:21)
    at Strapi.load (C:\Solutions\okr-strapi\node_modules\strapi\lib\Strapi.js:311:19)
    at async Strapi.start (C:\Solutions\okr-strapi\node_modules\strapi\lib\Strapi.js:190:9)
`

UPDATES done to compile

Before 
![image](https://user-images.githubusercontent.com/7934938/96354109-d81ab800-10ca-11eb-9d66-0de6d5301874.png)

After
![image](https://user-images.githubusercontent.com/7934938/96354113-e072f300-10ca-11eb-9eb7-a24d4dbc915d.png)

**Comment by GanizaniSitara** [comment]
DB config database.json file is expected in .\config, move it there instead of the environments folder.

Update packages to latest

npm install strapi-hook-bookshelf@latest --save-dev
npm install strapi-hook-knex@latest --save-dev

update config
![image](https://user-images.githubusercontent.com/7934938/96355241-58471a80-10d7-11eb-9800-6937125b4ce8.png)

The you'll hit error with strapi-connector-bookshelf coming out require-connector.js

Deprecated package https://www.npmjs.com/package/strapi-hook-bookshelf

install 

npm install strapi-connector-bookshelf@latest --save-dev

..... and running ... few hours well spent ... eh
